### PR TITLE
Add options + JSON schema

### PR DESCRIPTION
**Pull request by uwiger**
Added options for keyblock interval, microblock interval, and whether to auto-emit microblocks on tx push.

The options are defined in a JSON schema under `priv/`. The user-provided options from the aeternity config
(not checked during the ae node startup) are checked as the plugin application starts.

### CODE REVIEW

**Comment by uwiger** [comment]
Note that for now, the plugin will only work with PR aeternity/aeternity#3708

**Comment by nikita-fuchs** [comment]
@uwiger in order to turn the dev-mode into something more enduser-application-like, we would ideally need a REST API for the functionalities and the settings. By functionalities I mean things that are triggered "manually" . The idea is to have aestudio and other (local) (cli) applications remote-controlling the devmode, although it would have to be started manually at least once of course.

With that in mind, it should ideally be possible to change parameters. Which could also be wrapped in just restarting the devmode with new options and old state, if changing separate parameters in runtime leads to interferences and bugs.

A good inspiration here is looking at https://www.trufflesuite.com/ganache (see screenshots) and https://www.npmjs.com/package/ganache-cli (see commands) , their only big drawback is that they don't provide a REST api to easily have this running and configured somewhere remotely.

**Comment by uwiger** [comment]
So there is already a REST API (of sorts) as part of the demo web ux. I added a description of it in the README.

**Comment by nikita-fuchs** [comment]
> So there is already a REST API (of sorts) as part of the demo web ux. I added a description of it in the README.

Yes I saw that, it's a really good start that would be awesome to build upon. It would be great if all function(alitie)s/features/parameters would generically be exposed through a web API like this. Then a user could run this thing, and point a UI (e.g. in aestudio) towards it to do whatever is necessary.

**Comment by uwiger** [comment]
Currently, these are all parameters that the plugin recognizes. The full REST API of the node itself is of course available too.

**Review by velzevur — APPROVED** [review]

**Pull request merged**
